// HEADER
export const SET_HEADER_LINKS = 'SET_HEADER_LINKS';
export const SET_NAVBAR_LINKS = 'SET_NAVBAR_LINKS';
export const CHANGE_NAVBAR_ACTIVE = 'CHANGE_NAVBER_ACTIVE';

// USER
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';

// SHOP
export const SET_SHOP_CATEGORIES = 'SET_SHOP_CATEGORIES';
export const SET_SHOP_PRODUCTS = 'SET_SHOP_PRODUCTS';
export const FILTER_PRODUCTS_WITH_CATEGORY_ID = 'FILTER_PRODUCTS_WTH_CATEGORY_ID';
export const FILTER_PRODUCTS_WITH_QUERY = 'FILTER_PRODUCTS_WITH_QUERY';